<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="glados">
  <xacro:property name="wheel_separation" value="0.070" />
  <xacro:property name="wheel_radius" value="0.034" />
  <xacro:property name="wheel_width" value="0.010" />
  <xacro:property name="castor_radius" value="0.005" />
  <xacro:property name="body_height" value="0.05" />
  <xacro:property name="body_width" value="0.05" />
  <xacro:property name="body_length" value="0.1" />

  <!-- <link name="odom"/>

  <joint name="base_joint" type="fixed">
    <parent link="odom"/>
    <child link="base_link"/>
    <origin xyz="0.0 0.0 0.10" rpy="0 0 0"/>
  </joint> -->

  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="0.025" length="0.03"/>
        <!-- <box size="${body_length} ${body_width} ${body_height}"/> -->
      </geometry>
      <material name="Cyan">
        <color rgba="0 1.0 1.0 1.0"/>
      </material>
    </visual>

    <collision>
      <geometry>
        <cylinder radius="0.025" length="0.03"/>
        <!-- <box size="${body_length} ${body_width} ${body_height}"/> -->
      </geometry>
    </collision>

    <inertial>
      <mass value="0.18"/>
      <inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>
    </inertial>
  </link>

  <link name="wheelL">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.03"/>
      <inertia ixx="1.75e-5" ixy="0.0" ixz="0.0" iyy="1.75e-5" iyz="0.0" izz="1.75e-5"/>
    </inertial>
  </link>

  <link name="wheelR">
    <visual>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.03"/>
      <inertia ixx="1.75e-5" ixy="0.0" ixz="0.0" iyy="1.75e-5" iyz="0.0" izz="1.75e-5"/>
    </inertial>
  </link>

  <!-- <link name="castor">
    <visual>
      <geometry>
        <sphere radius="${castor_radius}"/>
      </geometry>
    </visual>

    <collision>
      <geometry>
        <sphere radius="${castor_radius}"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.05"/>
      <inertia ixx="1.75e-5" ixy="0.0" ixz="0.0" iyy="1.75e-5" iyz="0.0" izz="1.75e-5"/>
    </inertial>
  </link> -->

  <joint name="jointL" type="continuous">
    <parent link="base_link"/>
    <child link="wheelL"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 ${body_width/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <joint name="jointR" type="continuous">
    <parent link="base_link"/>
    <child link="wheelR"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 -${body_width/2 + wheel_width/2} 0" rpy="-${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint>

  <!-- <joint name="jointCastor" type="continuous">
    <parent link="base_link"/>
    <child link="castor"/>
    <axis xyz="0 0 1"/>
    <origin xyz="${body_length/2} 0 ${body_height*7/8 - body_height/2}" rpy="${pi/2} 0 0" />
    <dynamics friction="0.1"/>
  </joint> -->

</robot>